
title: enlow
description: This is a test site.
twitter_username: zombiedogz
github_username: zombiedogz

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
